#!/usr/bin/env bash
set -euo pipefail

# Trap Ctrl-C cleanly
trap 'echo -e "\nSetup cancelled." >&2; exit 1' INT TERM

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

echo "========================================"
echo "  Hermes Agent — TrueNAS Setup Wizard"
echo "========================================"
echo ""

# -----------------------------------------------
# 1. Data path
# -----------------------------------------------
read -rp "OTTO_DATA_PATH [/mnt/tank/otto/data]: " OTTO_DATA_PATH
OTTO_DATA_PATH="${OTTO_DATA_PATH:-/mnt/tank/otto/data}"
mkdir -p "${OTTO_DATA_PATH}"
echo "  -> Using data path: ${OTTO_DATA_PATH}"
echo ""

# -----------------------------------------------
# 2. UID / GID
# -----------------------------------------------
CURRENT_UID="$(id -u)"
CURRENT_GID="$(id -g)"
read -rp "HERMES_UID [${CURRENT_UID}]: " HERMES_UID
HERMES_UID="${HERMES_UID:-${CURRENT_UID}}"
read -rp "HERMES_GID [${CURRENT_GID}]: " HERMES_GID
HERMES_GID="${HERMES_GID:-${CURRENT_GID}}"
echo ""

# -----------------------------------------------
# 3. Dashboard credentials
# -----------------------------------------------
read -rp "Dashboard username [admin]: " DASH_USER
DASH_USER="${DASH_USER:-admin}"

DASH_PASS=""
while [[ -z "${DASH_PASS}" ]]; do
  read -rsp "Dashboard password (required): " DASH_PASS
  echo ""
  if [[ -z "${DASH_PASS}" ]]; then
    echo "  Error: password cannot be empty."
  fi
done

read -rp "Dashboard secret (leave blank to auto-generate 32-char secret): " DASH_SECRET
if [[ -z "${DASH_SECRET}" ]]; then
  # Generate a 32-char alphanumeric secret
  DASH_SECRET="$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32)"
  echo "  -> Auto-generated secret: ${DASH_SECRET}"
fi
echo ""

# -----------------------------------------------
# 4. Anthropic API key
# -----------------------------------------------
ANTHROPIC_API_KEY=""
while [[ -z "${ANTHROPIC_API_KEY}" ]]; do
  read -rsp "ANTHROPIC_API_KEY (required): " ANTHROPIC_API_KEY
  echo ""
  if [[ -z "${ANTHROPIC_API_KEY}" ]]; then
    echo "  Error: Anthropic API key cannot be empty."
  fi
done
echo ""

# -----------------------------------------------
# 5. Messaging platforms
# -----------------------------------------------
TELEGRAM_BOT_TOKEN=""
TELEGRAM_ALLOWED_USERS=""
DISCORD_BOT_TOKEN=""
DISCORD_ALLOWED_USERS=""
SLACK_BOT_TOKEN=""
SLACK_APP_TOKEN=""
SLACK_ALLOWED_USERS=""

echo "Which messaging platform(s) would you like to configure?"
echo "  1) Telegram"
echo "  2) Discord"
echo "  3) Slack"
echo "  4) None"
read -rp "Enter numbers separated by spaces (e.g. 1 2): " PLATFORMS
echo ""

for PLATFORM in ${PLATFORMS}; do
  case "${PLATFORM}" in
    1)
      read -rsp "TELEGRAM_BOT_TOKEN: " TELEGRAM_BOT_TOKEN; echo ""
      read -rp  "TELEGRAM_ALLOWED_USERS (comma-separated user IDs): " TELEGRAM_ALLOWED_USERS
      ;;
    2)
      read -rsp "DISCORD_BOT_TOKEN: " DISCORD_BOT_TOKEN; echo ""
      read -rp  "DISCORD_ALLOWED_USERS (comma-separated user IDs): " DISCORD_ALLOWED_USERS
      ;;
    3)
      read -rsp "SLACK_BOT_TOKEN: " SLACK_BOT_TOKEN; echo ""
      read -rsp "SLACK_APP_TOKEN: "  SLACK_APP_TOKEN;  echo ""
      read -rp  "SLACK_ALLOWED_USERS (comma-separated user IDs): " SLACK_ALLOWED_USERS
      ;;
    4)
      break
      ;;
    *)
      echo "  Warning: unrecognised option '${PLATFORM}', skipping."
      ;;
  esac
done
echo ""

# -----------------------------------------------
# 6. Tailscale
# -----------------------------------------------
USE_TAILSCALE=false
TS_AUTHKEY=""
TS_HOSTNAME="otto"
TS_EXTRA_ARGS=""

read -rp "Enable Tailscale? (y/n) [n]: " TS_CHOICE
TS_CHOICE="${TS_CHOICE:-n}"
if [[ "${TS_CHOICE,,}" == "y" ]]; then
  USE_TAILSCALE=true
  while [[ -z "${TS_AUTHKEY}" ]]; do
    read -rsp "TS_AUTHKEY (required): " TS_AUTHKEY; echo ""
    if [[ -z "${TS_AUTHKEY}" ]]; then
      echo "  Error: Tailscale auth key cannot be empty."
    fi
  done
  read -rp "TS_HOSTNAME [otto]: " TS_HOSTNAME
  TS_HOSTNAME="${TS_HOSTNAME:-otto}"
fi
echo ""

# -----------------------------------------------
# 7. Write .env
# -----------------------------------------------
cat > "${ENV_FILE}" <<EOF
# Generated by setup.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# === Paths ===
OTTO_DATA_PATH=${OTTO_DATA_PATH}
HERMES_UID=${HERMES_UID}
HERMES_GID=${HERMES_GID}

# === Dashboard ===
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DASH_USER}
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DASH_PASS}
HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DASH_SECRET}
DASHBOARD_HOST=0.0.0.0
DASHBOARD_PORT=9119

# === Anthropic ===
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# === Messaging ===
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
DISCORD_ALLOWED_USERS=${DISCORD_ALLOWED_USERS}
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
SLACK_ALLOWED_USERS=${SLACK_ALLOWED_USERS}

# === Tailscale ===
TS_AUTHKEY=${TS_AUTHKEY}
TS_HOSTNAME=${TS_HOSTNAME}
TS_EXTRA_ARGS=${TS_EXTRA_ARGS}
EOF

echo ".env written to ${ENV_FILE}"
echo ""

# -----------------------------------------------
# 8. Next steps
# -----------------------------------------------
if [[ "${USE_TAILSCALE}" == "true" ]]; then
  echo "========================================"
  echo "  Setup complete!"
  echo ""
  echo "  Start with Tailscale:"
  echo "    make up-ts"
  echo ""
  echo "  Access the dashboard via Tailscale:"
  echo "    http://<tailscale-ip>:9119"
  echo ""
  echo "  Note: ensure /dev/net/tun is enabled under"
  echo "  device passthrough in TrueNAS custom app settings."
  echo "========================================"
else
  echo "========================================"
  echo "  Setup complete!"
  echo ""
  echo "  Start the services:"
  echo "    make up"
  echo ""
  echo "  Access the dashboard:"
  echo "    http://<truenas-ip>:9119"
  echo "========================================"
fi
